source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '18.0'

target 'PreferabliDataSDK' do
    pod 'Alamofire'
    pod 'Mixpanel-swift'
end

post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '18.0'
               end
          end
   end
end
